config/routes.rb
UserTest::Application.routes.draw do

  devise_for :users, path_names: {sign_in: 'login', sign_out: 'logout'}
  root :to => 'home#show'

  resource :home, only: [ :index, :show ]

  resources :clusters, only: [ :index, :show ]
  resources :galaxies, only: [ :show ]
  resources :solar_systems, only: [ :show ]
  resources :planets, only: [ :show ]

  

end

app/models/cluster.rb
class Cluster < ActiveRecord::Base
  belongs_to :universe

  has_many :galaxies

  validates :name, :universe, presence: true
end

app/models/galaxy.rb
class Galaxy < ActiveRecord::Base
  belongs_to :cluster

  has_many :solar_systems

  validates :name, :cluster_id, presence: true
end

app/models/planet.rb
class Planet < ActiveRecord::Base
  belongs_to :user
  belongs_to :solar_system

  after_save :create_resources
  has_one :planet_resources, dependent: :destroy

  validates :name, :solar_system_id, presence: true

  def self.select_free_planet(user)
    Planet.transaction do
      planet = Planet.where( user_id: nil).sample
      planet.update_attribute(:user_id, user)
      planet
    end
  end

  private

  def create_resources
    self.planet_resources = PlanetResources.create
  end
end

app/models/planet_resource.rb
class PlanetResource
  attr_reader :population, :metal, :uranium, :arplax

  def initialize(params)
    @population = params[:population]
    @metal = params[:metal]
    @uranium = params[:uranium]
    @arplax = params[:arplax]
  end

  def population
    @population
  end

  def metal
    @metal
  end

  def uranium
    @uranium
  end

  def arplax
    @arplax
  end
end

app/models/planet_resources.rb
class PlanetResources < ActiveRecord::Base
  belongs_to :planet

  validates :planet_id, presence: true

  def resources
    update_resources

    PlanetResource.new({
        population: population,
        metal: metal,
        uranium: uranium,
        arplax: arplax
    })
  end

  private

  def population=(value)
    super
  end

  def population
    super.to_f
  end

  def metal=(value)
    super
  end

  def metal
    super.to_f
  end

  def uranium=(value)
    super
  end

  def uranium
    super.to_f
  end

  def arplax=(value)
    super
  end

  def arplax
    super.to_f
  end

  def update_resources
    old_attr = attributes.clone
    PlanetResources.transaction do
      time_diff = time_diff_in_hours
      update_attribute("population", calculate_population_diff(old_attr["population"], time_diff ))
      update_attribute("metal", old_attr["metal"] + metal_rate * time_diff)

      if uranium_rate > 0.0
        update_attribute "uranium", old_attr["uranium"] + uranium_rate * time_diff
      end

      if arplax_rate > 0.0
        update_attribute "arplax", old_attr["arplax"] + arplax_rate * time_diff
      end
    end
  end

  def time_diff_in_hours
    (Time.now - updated_at) / 3600 # seconds to hours
  end

  def calculate_population_diff(old_value, time_diff)
    old_value + (1000*time_diff)
  end
end

app/models/solar_system.rb
class SolarSystem < ActiveRecord::Base
  belongs_to :galaxy

  has_many :planets

  validates :name, :galaxy, presence: true
end

app/models/universe.rb
class Universe < ActiveRecord::Base
  has_many :clusters

  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :planets, dependent: :nullify

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :colonize_first_planet

  def current_planet
    raise "Player '#{email}' has no planets!" unless planets

    @current_planet ||= planets.first
  end

  def current_planet_resources
    raise "Player '#{email}' has no planets!" unless planets

    current_planet.planet_resources.resources
  end

  def visit_planet(planet)
    @current_planet = planet
  end

  private

  def colonize_first_planet
    planet = Planet.select_free_planet(self)
    planets << planet
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clusters_controller.rb
class ClustersController < ApplicationController
  def index
    @clusters = Cluster.paginate(page: params[:page], :per_page => 10)
  end

  def show
    @cluster = Cluster.find(params[:id])

    @galaxies = @cluster.galaxies.paginate(page: params[:page], :per_page => 10)
  end
end

app/controllers/galaxies_controller.rb
class GalaxiesController < ApplicationController
  def show
    @galaxy = Galaxy.find(params[:id])

    @systems = @galaxy.solar_systems.paginate(page: params[:page], :per_page => 20)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, except:[:index]

  def index

  end

  def show

  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @planets = Planet.paginate(page: params[:page], :per_page => 20)
  end

  def show
    @planet = Planet.find(params[:id])

    current_user.visit_planet @planet
  end
end

app/controllers/solar_systems_controller.rb
class SolarSystemsController < ApplicationController
  def show
    @system = SolarSystem.find(params[:id])

    @planets = @system.planets.paginate(page: params[:page], :per_page => 10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clusters_helper.rb
module ClustersHelper
end

app/helpers/galaxies_helper.rb
module GalaxiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/planet_helper.rb
module PlanetHelper
end

app/helpers/solar_systems_helper.rb
module SolarSystemsHelper
end

app/views/clusters/index.html.erb
<div>
  <h1>Cluster</h1>
</div>

<%= will_paginate %>

<table class="table table-striped table-bordered table-condensed">
  <thead>
  <tr>
    <th colspan="1" width="20">ID</th>
    <th colspan="5">Cluster</th>
  </tr>
  </thead>
  <tbody>
  <% @clusters.each do |cluster| %>
    <tr>
      <td><%= cluster.id %></td>
      <td><%= link_to cluster.name, cluster %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate %>

app/views/clusters/show.html.erb
<div class="hero-unit">
  <h1>Cluster <%= @cluster.name.capitalize %></h1>

  <p class="center"><%= link_to "All clusters", clusters_path %></p>
</div>

<%= will_paginate @galaxies %>

<table class="table table-striped table-bordered table-condensed">
  <thead>
  <tr>
    <th colspan="1" width="20">ID</th>
    <th colspan="5">Galaxy</th>
  </tr>
  </thead>
  <tbody>
  <% @galaxies.each do |galaxy| %>
    <tr>
      <td><%= galaxy.id %></td>
      <td><%= link_to galaxy.name.capitalize, galaxy %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate @galaxies %>

app/views/galaxies/show.html.erb
<div class="hero-unit">
  <h1>Galaxy <%= @galaxy.name %></h1>

  <p class="center">Cluster: <%= link_to @galaxy.cluster.name.capitalize, @galaxy.cluster %></p>
</div>

<%= will_paginate @systems %>

<table class="table table-striped table-bordered table-condensed">
  <thead>
  <tr>
    <th colspan="1" width="20">ID</th>
    <th colspan="5">Solar System</th>
  </tr>
  </thead>
  <tbody>
  <% @systems.each do |system| %>
    <tr>
      <td><%= system.id %></td>
      <td><%= link_to system.name.capitalize, system %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate @systems %>

app/views/home/index.html.erb
Hello User

app/views/home/show.html.erb
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th colspan="1" width="20">ID</th>
      <th colspan="5">Full Name</th>
    </tr>
  </thead>
  <tbody>
    <% current_user.planets.each do |planet| %>
      <tr>
        <td><%= planet.id %></td>
        <td><%= link_to planet.name, planet %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar navbar-fixed-tope navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <!--<div class="nav=collapse collapse">-->
            <ul class="nav">
              <% if user_signed_in? %>
                <li class="inverse-li">Logged in as <strong><%= current_user.email %></strong></li>
                <li class><%= link_to 'Edit profile', edit_user_registration_path %></li>
                <li class><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <%= link_to "Sign up", new_user_registration_path %>
                <%= link_to "Login", new_user_session_path %>
              <% end %>
            </ul>
            <% if user_signed_in? %>
            <%   current_resources = current_user.current_planet_resources %>
              <div class="pull-right">
                  <ul class="nav">
                    <li><div class="nav-resources">Population: <%= current_resources.population.floor %></div></li>
                    <li><div class="nav-resources">Metal: <%= current_resources.metal.floor %></div></li>
                    <li><div class="nav-resources">Uranium: <%= current_resources.uranium.floor %></div></li>
                    <li><div class="nav-resources">Arplax: <%= current_resources.arplax.floor %></div></li>
                  </ul>
              </div>
            <% end %>
          <!--</div>-->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <% if notice || alert %>
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        <% end %>

        <% if user_signed_in? %>
          <div class="span3">
            <ul class="nav nav-list">
              <li><%= link_to "Home", root_path %></li>
            </ul>
          </div>
        <% end %>

        <div class="span9">
          <%= yield %>
          <%= debug(params) if Rails.env.development? %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/planets/index.html.erb
<%= will_paginate %>

<table class="table table-striped table-bordered table-condensed">
  <thead>
  <tr>
    <th colspan="1" width="20">ID</th>
    <th colspan="5">Full Name</th>
  </tr>
  </thead>
  <tbody>
  <% @planets.each do |planet| %>
    <tr>
      <td><%= planet.id %></td>
      <td><%= link_to planet.name, planet %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate %>

app/views/planets/show.html.erb
<div class="hero-unit">
  <h1>Planet <%= @planet.name %></h1>

  <p class="center">Solar System: <%= link_to @planet.solar_system.name.capitalize, @planet.solar_system %></p>
</div>

app/views/solar_systems/show.html.erb
<div class="hero-unit">
  <h1>System <%= @system.name %></h1>

  <p class="center">Galaxy: <%= link_to @system.galaxy.name.capitalize, @system.galaxy %></p>
</div>

<%= will_paginate @planets %>

<table class="table table-striped table-bordered table-condensed">
  <thead>
  <tr>
    <th colspan="1" width="20">ID</th>
    <th colspan="5">Planet</th>
  </tr>
  </thead>
  <tbody>
  <% @planets.each do |planet| %>
    <tr>
      <td><%= planet.id %></td>
      <td><%= link_to planet.name.capitalize, planet %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate @planets %>